In [18]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv"
df = pd.read_csv(url)

In [2]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
(df['Outcome'] == 0).sum()

np.int64(500)

In [4]:
cols_with_zeros = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

In [19]:
for x in cols_with_zeros:
    print('la colonna', x, 'ha', (df[x]==0).sum(),'zeri')

la colonna Glucose ha 5 zeri
la colonna BloodPressure ha 35 zeri
la colonna SkinThickness ha 227 zeri
la colonna Insulin ha 374 zeri
la colonna BMI ha 11 zeri

In [20]:
for x in cols_with_zeros:
    df[x] = df[x].replace(0,np.nan)

In [21]:
for x in cols_with_zeros:
    print('la colonna', x, 'ha', (df[x]==0).sum(),'zeri')

la colonna Glucose ha 0 zeri
la colonna BloodPressure ha 0 zeri
la colonna SkinThickness ha 0 zeri
la colonna Insulin ha 0 zeri
la colonna BMI ha 0 zeri

In [22]:
for x in cols_with_zeros:
    print('la colonna', x, 'ha', df[x].isnull().sum(),'valori nulli')

la colonna Glucose ha 5 valori nulli
la colonna BloodPressure ha 35 valori nulli
la colonna SkinThickness ha 227 valori nulli
la colonna Insulin ha 374 valori nulli
la colonna BMI ha 11 valori nulli

In [16]:
#for x in cols_with_zeros:
 #   median = df[x].median()
 #   df[x] = df[x].fillna(median)

In [23]:
for col in cols_with_zeros:
    df[col] = df.groupby('Outcome')[col].transform(
        lambda x: x.fillna(x.median())
    )

print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [24]:
y = df['Outcome']

In [28]:
x = df.drop('Outcome',axis=1)

In [29]:
x.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148.0,72.0,35.0,169.5,33.6,0.627,50
1,1,85.0,66.0,29.0,102.5,26.6,0.351,31
2,8,183.0,64.0,32.0,169.5,23.3,0.672,32
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33

In [34]:
!pip install --upgrade --force-reinstall scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp312-cp312-win_amd64.whl.metadata (11 kB)
Collecting numpy>=1.24.1 (from scikit-learn)
  Using cached numpy-2.4.6-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.17.1-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.22.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.9.0-cp312-cp312-win_amd64.whl (8.2 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.22.0-py3-none-any.whl (453 kB)
Using cached numpy-2.4.6-cp312-cp312-win_amd64.whl (12.3 MB)
Using cached scipy-1.17.1-cp312-cp312-win_amd64.whl (36.5 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, numpy, narwhals, joblib, scipy, scikit-learn

  Attempting uninstall: threadpoolctl

    Found existing installation: threadpoolctl 3.6.0

    Uninstalling threadpoolctl-3.6.0:

   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
      Successfully uninstalled threadpoolctl-3.6.0
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
   ---------------------------------------- 0/6 [threadpoolctl]
  Attempting uninstall: numpy
   ---------------------------------------- 0/6 [threadpoolctl]
   ------ --------------------------------- 1/6 [numpy]
    Found existing installation: numpy 2.4.6
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
    Uninstalling numpy-2.4.6:
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
      Successfully uninstalled numpy-2.4.6
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
   ------ --------------------------------- 1/6 [numpy]
  Attempting uninstall: narwhals
   ------ --------------------------------- 1/6 [numpy]
    Found existing installation: narwhals 2.22.0
   ------ --------------------------------- 1/6 [numpy]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
   ------------- -------------------------- 2/6 [narwhals]
    Uninstalling narwhals-2.22.0:
   ------------- -------------------------- 2/6 [narwhals]
      Successfully uninstalled narwhals-2.22.0
   ------------- -------------------------- 2/6 [narwhals]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\si.poggi\AppData\Local\Programs\Python\Python312\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\si.poggi\AppData\Local\Programs\Python\Python312\Lib\site-packages\~umpy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\si.poggi\AppData\Local\Programs\Python\Python312\Lib\site-packages\~klearn'.
  You can safely remove it manually.

In [35]:
from sklearn.model_selection import train_test_split

In [37]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [38]:
from sklearn.preprocessing import StandardScaler

In [63]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [44]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)

In [53]:
from sklearn.metrics import accuracy_score, confusion_matrix,precision_score, recall_score,f1_score,roc_curve, roc_auc_score
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

0.7727272727272727

In [57]:
y_prob_1 = model.predict_proba(x_test)[:,1]
y_prob_0 = model.predict_proba(x_test)[:,0]

fpr, tpr, thresholds = roc_curve(y_test, y_prob_1)
roc_auc = roc_auc_score(y_test,y_prob_1)
print(f"ROC-AUC: {roc_auc:.2f}")

ROC-AUC: 0.84

In [60]:
from sklearn.tree import DecisionTreeClassifier

In [72]:
#decision tree
model = DecisionTreeClassifier()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test,y_pred)
print("l'accuracy è:", accuracy)

y_prob = model.predict_proba(x_test)[:,1]
roc_auc = roc_auc_score(y_test,y_prob)
print(f"L'auc score è: {roc_auc:.2f}")

l'accuracy è: 0.8246753246753247
L'auc score è: 0.82

In [78]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test,y_pred)

y_pred_prob = model.predict_proba(x_test)[:,1]
roc_auc = roc_auc_score(y_test,y_pred_prob)

print(f"l'accuracy è: {accuracy}")
print(f"l'auc score è: {roc_auc:.2f}")

l'accuracy è: 0.8766233766233766
l'auc score è: 0.94

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
model = GradientBoostingClassifier()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)


accuracy = accuracy_score(y_test,y_pred)

y_pred_prob = model.predict_proba(x_test)[:,1]
roc_auc = roc_auc_score(y_test,y_pred_prob)

print(f"L'accuracy è: {accuracy}")
print(f"l'auc score è: {roc_auc:.2f}")

L'accuracy è: 0.8701298701298701
l'auc score è: 0.94